### PR TITLE
Integrate plugin_test job into workflow

### PR DESCRIPTION
**Pull request by jeffryang24**
## Summary

- Add `plugin_test` job.
- Bump checkout action to v2.
- Change single quote to double quote.

Solve asdf-community/.github/issues/2 for ninja build. :bowing_man:

### CODE REVIEW

**Comment by imbsky** [comment]
Great! Thank you! We added `plugin_test` step, so we can remove the `build` step. Could you update this PR?

**Comment by jeffryang24** [comment]
> Great! Thank you! We added `plugin_test` step, so we can remove the `build` step. Could you update this PR?

Sure... :+1:

**Comment by jeffryang24** [comment]
> Great! Thank you! We added `plugin_test` step, so we can remove the `build` step. Could you update this PR?

Did you mean the `build` job? cmiiw.

**Comment by imbsky** [comment]
I'm sorry! Yes!

**Comment by imbsky** [comment]
By the way, you have contributed to asdf community before. We have transferred some plugins to this organization. and we need a few maintainers. Your experience level doesn't matter, so if you have time, I would like to invite you as a maintainer.

**Comment by jeffryang24** [comment]
> By the way, you have contributed to asdf community before. We have transferred some plugins to this organization. and we need a few maintainers. Your experience level doesn't matter, so if you have time, I would like to invite you as a maintainer.

Yes, It's a great opportunity for me to help managing the asdf-community repository. I also learn something new about the github action from contributing to this repository. Thank you so much. :bowing_man:

**Comment by imbsky** [comment]
Thank you, too! Many open source contributions focus on major additions and bug fixes, but I think the most important thing is to continue contributing to the community!

**Comment by imbsky** [comment]
Thanks @jeffryang24 for your contribution, and welcome to the asdf-community!

**Comment by jeffryang24** [comment]
> Thanks @jeffryang24 for your contribution, and welcome to the asdf-community!

You are welcome... :bowing_man:

**Comment by imbsky** [comment]
@all-contributors please add @jeffryang24 for infra

**Pull request merged**
